services:
  # 前端服務
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # 後端服務
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - /app/__pycache__
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge